---

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_HOST: tcp://ip172-18-0-18-b9lnuhe9a8q000auh8og.direct.labs.play-with-docker.com:2375

stages:
  - build-war
  - build-image
  - deploy


build:
  stage: build-war
  image: maven:3-jdk-8
  variables:
    ENV: prod
  tags:
    - docker
  cache:
    key: "$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - .m2
  script:
   #- mvn verify
    - export MAVEN_OPTS="-Dmaven.repo.local=.m2"
    - mvn clean install -Dspring.profiles.active=${ENV}
  artifacts:
    paths:
      - target/*.war
    expire_in: 2d
  only:
    - master

# build-war:
#   stage: build-war
#   image: maven:3-jdk-8
#   variables:
#     ENV: prod
#   tags:
#     - docker
#   script:
#     #- export MAVEN_OPTS="-Dmaven.repo.local=/cache/maven"
#   artifacts:
#     paths:
#       - target/*.war
#     expire_in: 2d
#   only:
#     - master

build-image:
  image: tmaier/docker-compose
  stage: build-image
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - export DOCKER_HOST=$DOCKER_HOST
    - docker-compose up -d
    # - docker run -p 8080:8080 $IMAGE_TAG
  only:
    - master


# deploy-image:
#   image: docker
#   stage: deploy
#   tags:
#     - docker
#   script:
#   only:
#     - master