---

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  # - build
  - deploy

build:
  stage: build
  image: maven:3-jdk-8
  tags:
    - docker
  cache:
    key: "$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - .m2
  script:
   #- mvn verify
    - export MAVEN_OPTS="-Dmaven.repo.local=.m2"
    - mvn clean install -Dspring.profiles.active=prod
  artifacts:
    paths:
      - target/*.war
    expire_in: 2d

deploy-to-docker:
  image: tmaier/docker-compose
  stage: deploy
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - export DOCKER_HOST=$DOCKER_HOST
    - docker-compose pull
    - docker-compose up -d
    # - docker run -p 8080:8080 $IMAGE_TAG
  only:
    - master

deploy-to-server:
  stage: deploy
  tags:
    - docker
  image: ansible/centos7-ansible
  script:
    - cd ansible
    - ansible-playbook deploy.yml -l $CI_COMMIT_REF_NAME -e  archive_file=./target/*war