---

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - test
  - build

cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true


test:
  stage: test
  image: maven:3-jdk-8
  tags:
    - docker
  script:
    - export MAVEN_OPTS="-Dmaven.repo.local=/cache/maven"
    - mvn verify

build-war:
  stage: build
  image: maven:3-jdk-8
  tags:
    - docker
  script:
    - export MAVEN_OPTS="-Dmaven.repo.local=/cache/maven"
    - mvn clean install -Dspring.profiles.active=${ENV}
  environment:
    name: prod
    url: ${APP_URL_DEV}
  artifacts:
    paths:
      - target/*.war
    expire_in: 2d
  only:
    - master

build-image:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
