---

stages:
  - test
  - build


test:
  stage: test
  image: maven:3-jdk-8
  tags:
    - docker 
    - shared
    - java
  script:
    - export MAVEN_OPTS="-Dmaven.repo.local=/cache/maven"
    - mvn verify
 
build:
  stage: build
  variables:
    ENV: dev
  image: maven:3-jdk-8
  tags:
    - docker
    - shared
    - java
  script:
    - export MAVEN_OPTS="-Dmaven.repo.local=/cache/maven"
    - mvn clean install -Dspring.profiles.active=${ENV}
    - mv target/*.war target/${WAR_NAME}
  environment:
    name: dev
    url: ${APP_URL_DEV}
  artifacts:
    paths:
      - target/*.war
    expire_in: 2d
  only:
    - master
