- hosts: all
  vars:
    TOMCAT_VERSION: 8.5.3
    TOMCAT_MAJOR: 8
    ROOT_DIR: "/var/lib"
    TOMCAT_HOME: "{{ ROOT_DIR }}/tomcat"
    CATALINA_HOME: "{{ TOMCAT_HOME }}"
  tasks:
    - name: install openjdk
      apk:
        name: openjdk8
        state: present
        update_cache: yes

    - name: install curl
      package:
        name: tar
        state: present

    - name: create tomcat dir
      file:
        path: "{{ ROOT_DIR }}"
        state: directory
        
    - name: get tomcat
      unarchive:
        src: "http://archive.apache.org/dist/tomcat/tomcat-{{TOMCAT_MAJOR}}/v{{TOMCAT_VERSION}}/bin/apache-tomcat-{{TOMCAT_VERSION}}.tar.gz"
        dest: "{{ TOMCAT_HOME | dirname }}"
        remote_src: yes

    - name: link tomcat
      file:
        src: "{{ ROOT_DIR }}/apache-tomcat-{{ TOMCAT_VERSION }}"
        dest: "{{ TOMCAT_HOME }}"
        state: link

    - name: start catalina
      command: "{{ TOMCAT_HOME }}/bin/catalina.sh start"

    - name: copy war
      copy:
        src: "../target/spring-base-1.0.war"
        dest: "{{ TOMCAT_HOME }}/webapps"
